89luca89/distrobox

distrobox-enter

Fix a regression I've introduced in commit: enter: [simplify env passing](https://github.com/89luca89/distrobox/commit/7b2585d39018a01295c60d74350b37479f864273)
On some host systems (eg: Fedora) we have multiline env variables like:
```
BASH_FUNC_which%%=() {  ( alias;
eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot "$@"
}
```
This is not supported in podman (or docker) env, so we need to filter those out

Fix env passing

---

distrobox-create
distrobox-enter
distrobox-export
distrobox-init
install

Work to fix #19 
in some cases we want to symlink what it's already a symlink
so we should use `realpath` to link the original file always

init: check if file exists before linking and link it's realpath

---

distrobox-create
distrobox-init

Right now in `create` we mount `/` as `/run/host/` inside the container
this is ok for later bind-mounts but for some files it is causing problems
One of them is `/etc/resolv.conf` that is a symlink when it's managed by `systemd-resolved`
As some setups do relative links like:
`lrwxrwxrwx. 1 root root unconfined_u:object_r:net_conf_t:s0 39 Nov 15 10:39 /etc/resolv.conf -> ../run/systemd/resolve/stub-resolv.conf`
And others do absolute links like:
`lrwxrwxrwx. 1 root root system_u:object_r:net_conf_t:s0 32 Dec 6 18:13 /etc/resolv.conf -> /run/systemd/resolve/resolv.conf`
(NOTE: both of them are from a fresh Fedora 35 workstation installation)
The absolute links will **fail** inside the container, so during the `init` phase, we have problems (for eg: no internet access)
Solution:
Move this …

create/init: move mounting of dynamic configs from init to create

---

distrobox-export

Add support for exporting a binary directly to the host:
`--bin` using the binary absolute path
`--export-path` the destination where to export it
This goes together also with `--delete` to undo an export, and `--extra-flags` to add additional flags to it.
Examples:
`distrobox-export --bin /usr/bin/vim --export-path ~/.local/bin/`
Will create this file with executable permission:
`~/.local/bin/vim` 
```
#!/bin/sh
if [ ! -f /run/.containerenv ]; then
distrobox-enter --name ubuntu-21 -e /usr/bin/vim  $@
else
/usr/bin/vim $@
fi
```
this could be used in conjunction with your `$PATH` to simply export your binary globally, or with custom directories together with `direnv` to create project-specific exports.
For example:
```
echo "PATH_add $PWD/.distrobox-bin" > .envrc
direnv allow …
```

export: Add direct export of binary #11

---

README.md

As I tested distrobox on Gentoo during #11 and still use it, I think we can add Gentoo to the list.

Add Gentoo to supported host distros

---

distrobox-create

Fix #47 
Use prune in the find, as exclude will still look into the excluded paths

create: fix endless find when gvfs volumes are mounted

---

distrobox-create

Fix #49 
Seems like sometimes $HOME points to traditional /home/username (which is a symlink to /var/home/username) and 
sometimes $HOME points directly to /var/home/username
At this point we should check so we can support both possibilities

create: fix difference between HOME and PWD path resolution, only if there is a difference

---

distrobox-create
distrobox-enter
distrobox-export
distrobox-init
install

I'm not a lawyer, but IMHO a license header in each script looks more professional :sweat_smile: and maybe in line with some policy.

Add license header and SPDX-License-Identifier

---

distrobox-init

init: use different check for user existence

---

README.md
distrobox-init

There are still a lot of bugs with NixOS which I am working to iron out, such as the following:
* Distrobox cannot be installed in /nix/store, not a huge deal, but very nice to have.
* Container distros don't support sudo, I don't no why, I just get an error whenever I try to become a super user.
* Kali does not come with DPKG or apt preinstalled, again I don't know why, but it is a pretty important feature of Kali
However, I was able to imporve NixOS support with this PR. I changed distrobox-init so that it recognizes symbolicly linked dotfiles, which many NixOS users (including myself) have. ﻿

Improve support for NixOS, and add more info about NixOS support to README.

---

docs/README.md

Proper syntax for installing packages with `yay` is `yay -S $PKG_NAME`.

Update README: Arch installation

---

distrobox-init

I don't know if this introduces some other issue, but now CentOS Stream 9 and RH UBI8 don't show the reported messages anymore

Fix for #60

---

man/gen-man

Self explanatory title. I have updated the `gen-man` script to exit if `ronn` is not installed.

gen-man: exit if dependency is not met

---

distrobox-init

If the user uses a custom HOME folder that does not contain anything,
the permissions of `$HOME/.local/share` are messed up:
```
$ ls -al $HOME/.local/share
total 20
drwxr-xr-x  5 root   root   4096 Jan 19 12:54 .
drwxr-xr-x  3 root   root   4096 Jan 19 12:54 ..
drwxr-xr-x  3 nobody nobody 4096 Dec 13 08:05 fonts
drwxr-xr-x 12 nobody nobody 4096 Dec 13 08:05 icons
drwxr-xr-x  5 nobody nobody 4096 Dec 13 08:05 themes
```
This impacts certain software that needs to write to `$HOME/.local/share`,
such as fish shell, which saves the user's command history there.
Fix up the permissions of `$HOME/.local` and `$HOME/.local/share` in the
same manner as the themes, icons, and fonts folders so that the
container's user can read and write to those folders freely:
```
$ ls -al $HOME/.local/share …
```

distrobox-init: Fix permissions of $HOME/.local/share

---

distrobox-create
distrobox-export

In a Fedora VM that I created on my MacBook Air, `/etc/hostname` is empty,
which means the container's hostname ends with just a period, which
looks odd:
```
$ cat /etc/hostname
$ ./distrobox enter -n fedora -- cat /etc/hostname
fedora.
```
Prefer `uname -n`, which shows the host machine's hostname properly.
```
$ uname -n
fedora
$ ./distrobox enter -n fedora -- uname -n
fedora.fedora
$ ./distrobox enter -n fedora -- cat /etc/hostname
fedora.fedora
```
`uname` is described by POSIX and should be available by default on every
modern Linux system, as it is typically a part of the coreutils package.
Link: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/uname.html

create/export: Prefer 'uname -m' to /etc/hostname

---

distrobox-init

When using a container image that has `dpkg` installed in it that is not
`apt` based (such as Arch Linux), there is an error entering the container
for the first time:
```
$ distrobox create -i ghcr.io/nathanchance/dev/arch -n dev-arch
$ distrobox enter --name dev-arch
Starting container dev-arch
run this command to follow along:
podman logs -f dev-arch
2022-01-20T16:05:25.003933000-07:00 /usr/sbin/mount
2022-01-20T16:05:25.004121000-07:00 /usr/sbin/mount
2022-01-20T16:05:25.004326000-07:00 /usr/sbin/passwd
2022-01-20T16:05:25.004505000-07:00 /usr/sbin/sudo
2022-01-20T16:05:25.004662000-07:00 /usr/sbin/useradd
2022-01-20T16:05:25.004808000-07:00 /usr/sbin/usermod
2022-01-20T16:05:25.004952000-07:00 /usr/sbin/fish
2022-01-20T16:05:25.123743000-07:00 Error: An error occurred
An error …
```

init: Check existence of /etc/apt/apt.conf.d

---

distrobox-init

Commit 0550f86 ("init: check if find is installed") aimed to check that
find was installed but it duplicated the check for mount instead.
Fix the check to look for find and mention that find is required in the
comment below.

init: Fix check for find

---

distrobox-create
distrobox-enter
docs/usage/distrobox-create.md
docs/usage/distrobox-enter.md
man/man1/distrobox-create.1
man/man1/distrobox-enter.1
man/man1/distrobox.1

Adding additional volumes of flags to the container manager command is useful for more advanced use of the tool.
The most common flag is `--volume` which should be just a pass-trough to the container manager command.
For anything else, provide a `--additional-flags` 
This involves both `create` and `enter`
Example usages:
`distrobox create --image fedora:35 --name test --volume /opt/my-dir:/usr/local/my-dir:rw --additional-flags "--pids-limit -1"`
`distrobox-enter  --additional-flags "--preserve-fds" --name test -- bash -l`
To pass additional environments variable, it is possible to use both additional-flags and the normal env export:
`MY_VAR=value distrobox-enter  --additional-flags "--preserve-fds" --name test -- bash -l`
`distrobox-enter  --additional-flags "--env MY_VAR=value" --name …

Support for additional volumes and flags

---

docs/posts/run_latest_gnome_kde_on_distrobox.md

Changed `fedora rawhide` to `fedora-rawhide` and fixed the session file name.

docs: typo fix

---

distrobox-create
distrobox-enter

I removed the `--name` flag from the output message in `distrobox-create` and `distrobox-enter` making it straight to the point.

create, enter: more concise messages

---

distrobox-create

Currently Distrobox points to real path of files like `distrobox-init distrobox-export localtime`, but by nature NixOS's store changes hashes and paths that were used to create container become invalid and forces user to do an annoying process of exporting image and importing it again to recreate container while keeping data. 
After applying patch distrobox will store and use files in `$HOME/.local/distrobox/$CONTAINER_NAME` instead to allow painless OS upgrades to occur. It won't make any difference to already created distrobox containers. But you to change export or init you will need to edit local file or recreate container.

[Improvement] NixOS system upgrade breakage fix

---

distrobox-enter

Change adds helper function `append_env` and appends default FHS values to `XDG_DATA_DIRS XDG_CONFIG_DIRS` envs, this fixes VSCode's file picker and Nautilus when running Archlinux container on NixOS as host.

[Improvement] XDG_.*_DIRS environment fixes

---

install

Previous install output would be like this `Be sure that /usr/local/bin. is in your $PATH environment variable for it to work.`. I have removed the trailing dot right after the path.

install: remove redundant dot

---

install

1caa478c52786 tried to improve the writeability check to avoid false
positives, such as the one reported in a DistroWatch.com article.
However, it is still possible to break this check by having the
destination and its parent directory not exist:
```
$ ./install -p $HOME/tmp/directory-does-not-exist/bin
Cannot write into /home/nathan/tmp/directory-does-not-exist/bin, permission denied.
```
The script already uses `install -D`, which will create the target
directory if it does not exist, so trying to create `dest_path`
preemptively only increases the complexity of install and risks
introducing false positive errors like above.
Instead, just check the calls to install and print a message about
potential issues with permissions if they fail.

install: Remove permissions check and dest_path creation

---

distrobox-init

This fixes #175 where home field in /etc/passwd diverges from value of $HOME
which then causes unexpected behaviour.
When user is pre-prepopulated due to some reason the old behaviour was to skip useradd.
So path in /etc/passwd could be different than one manually set (ex. when user asks for custom home).
Fix bug by force-setting properties with _usermod_ if user already exists.

init: If user already exists in /etc/passwd set props again, do not skip

---

distrobox-enter
docs/README.md
install
uninstall

I have added the `--prefix` option to both installer and uninstaller.
Main installation path should now be `$prefix/bin` and man path should be `$prefix/share/man`.
`-p` still exists for backwards compatibility and both scripts make sure only "one is present".

Prefix install/uninstall option

---

distrobox-enter

Despite tight integration, some host workdir paths may not exist in container.
So always drop at workdir through '/run/host' path which is bound to exist.
User can then cd as desired.
This also avoids some confusion. For example:
```
user@host:/etc$
user@host:/etc$ distrobox-enter guest
user@guest:/etc$ 
```
`/etc` on line-1 and `/etc` on line-3 are two different directories. 
It's not very intuitive that the working directory has changed while name remains identical.
Especially when for a different starting path we see different behaviour :
```
user@host:/home/user$
user@host:/home/user$ distrobox-enter guest
user@guest:/home/user$
```
Here the `/home/user` on line-1 and `/home/user` on line-3 _are the same_ directory. 
With this pull request, on enter, user will always drop to the same …

enter: Enter at workdir through child path of '/run/host'

---

distrobox-init

Right now the host's $SHELL integration is performed in a mandatory way, so it the $SHELL of host is not available in container's repositories, the whole init will fail
This patch will make the integration optional, falling back to bash when $SHELL is unavailable in container's repos.
Fix #185

init: check shell_pkg separately and fallback to bash in case of failure #185

---

distrobox-init

my host linux user is a single character (aka "d"), `distrobox-init` was failing to create user and group because the character `d` matches many users and groups. This fix ensure very short usernames are handled correctly. 
I've tested it only in a Centos 7 container, but it should work on other distros.

Fix grep match of very short user or group names.

---

distrobox-create

As of now, rootless docker prevents  host network, pid and ipc so we cannot do an unprivileged docker like on podman
But this means docker is running as root, and the root inside the container corresponds to the one on the host
Having passwordless sudo here can be dangerous, so let's make docker behave more similarly to how the rootless podman version works:
Let's mount /run/host, /sys, /proc and /dev as readonly, leave only selected paths as read-write like: /media /mnt /run/media /srv /tmp
This is a work to fix #201

WIP: Fix/201

---

distrobox-enter

The PATH fixes in 6b60c73999c5147f732a1f9933d0b52d7d090161 use the
host's $PATH instead of the $PATH defined in the container.  This
change fixes that by inspecting the container and parsing $PATH
out of its environment.  The inspect was already being done so
this shouldn't be a signficiant performance impact.  Future
features may desire further information out of the inspect
invocation and the parsing method can be extended.
The container's $PATH is merged with the host $PATH and the
standard set of binary paths as the existing logic uses.

fix: use container's $PATH when entering

---

.github/workflows/compatibility.yml
distrobox-create
distrobox-enter
distrobox-init
distrobox-list
distrobox-rm
distrobox-stop
docs/README.md

Implement use of environment variables to change defaults like:
- container manager
- default image to use
- default name to use
- default custom home to use
- interactivity
Variables will be respectively:
- DBX_CONTAINER_CUSTOM_HOME
- DBX_CONTAINER_MANAGER
- DBX_CONTAINER_IMAGE
- DBX_CONTAINER_NAME
- DBX_NON_INTERACTIVE
This work will open support for future configuration rc-style files,
which can be simply sourced.
For now this will ensure the possibility to alter the defaults using
environment files, lowering the need to use flags in normal use.
---
Simple use:
Add this to your ~/.profile
```sh
export DBX_CONTAINER_IMAGE="ubuntu:22.04"
export DBX_CONTAINER_MANAGER="docker"
export DBX_CONTAINER_NAME="test-env"
export DBX_CONTAINER_CUSTOM_HOME=/tmp/test-home
```
Now you can simply use:
- …

WIP: support environment variables to change defaults

---

.github/workflows/compatibility.yml
distrobox-create

Fix #215
Right now systemd integration works only on docker, on podman it will
fail.
This is because docker daemon, running as root, has access to
/sys/fs/cgroup, while podman (rootless) does not.
Podman has a functionality to set up cgroups so that they work in
rootless mode as explained here: https://www.redhat.com/sysadmin/improved-systemd-podman
Right now the system is not triggered because it only checks if
entrypoint are `/sbin/init` or `/usr/bin/systemd`.
To fix this, let's force the use of systemd mode on podman if we're
using `--init`.
This problem went also undetected on the new CI as the `init` images are
tested as normal images. Let's also fix this and test create/enter on
init images using systemd commands.

Fix compatibility with init containers

---

distrobox-init

The problem is that a user might have the first two directories on Arch
Linux if they have installed the `rpm` and `dpkg` commands respectively.
While that seems odd on the surface, these tools are useful for building
packages for `rpm` or `dpkg`-based distributions on Arch Linux, such as the
Linux kernel, which has `bindeb-pkg` and `binrpm-pkg` targets to build a
`.deb` and `.rpm` package respectively, which does not require a Debian or
Fedora host.
As a result of the `rpm` and `dpkg` directories being checked first, the
third else if clause never gets executed in the scenario described
above. Move the libalpm check to the beginning so that `pacman`-based
images benefit from the new change regardless of `rpm` and `dpkg` being
installed. While here, add a comment similar to the other …

init: Allow all package manager checks to run

---

distrobox-enter

The --dry-run switch for enter command fails with
```
DISTROBOX_ENTER_PATH=/usr/bin/distrobox-enter"'
++ set +o xtrace
/usr/bin/distrobox-enter: line 279: container_PATH: unbound variable
```
generate_command expects container_PATH to be declared, so move the
variable declaration slightly upper fixes the problem.

enter: fix unbound variable with --dry-run

---

distrobox-enter

Fixed a bash option that would result in "bashl" instead of "bash -l".

Fixed typo in bash option

---

docs/posts/execute_commands_on_host.md

Add tutorial for fish in execute_commands_on_host.md

---

install

As pointed out by Mišo Barišić in #260, this call might fail when
running `sudo ./install` because of the fix for CVE-2022-24765, which is
present in git 2.36.0 and certain maintenence releases from 2.30 to
2.35. This variable has been unused in this block since 68df9d2, where a
proper version value was used, rather than being dynamically updated by
`./install`.
Link: https://lore.kernel.org/xmqqv8veb5i6.fsf@gitster.g/

install: Stop calling git

---

distrobox-init

This pull request does the following:
1) fix openSUSE systemd (i.e., --init) enabled distrobox
2) customize openSUSE images during init, for enabling recommended packages
3) make it possible to keep recommended packages disabled --if one really wants that-- and do it in a way that is generic and can be used by other distroboxes and for other things
About 2 and 3, the first `enter` in a distrobox with is now quite a bit slower (because zypper is quite slow itself :-( ), but I think it's worth it. In fact, the resulting distrobox is now actually useful. E.g., GUI apps (but also non-GUI apps, as even just vim has problem withou recommended packages!) now works pretty much out of the box, once installed.
For comparison, I've created a Tumbleweed based distrobox, installed neofetch, vim and …

Some openSUSE improvement

---

distrobox-create
distrobox-enter
distrobox-init
docs/usage/distrobox-create.md
docs/usage/distrobox-init.md
docs/useful_tips.md

This implements support for running commands prior to most of the
container initialization. e.g. for RHEL and derivatives you might need
to pre-enable the PowerTools/CRB and EPEL repositories.
Resolves: https://github.com/89luca89/distrobox/issues/220
```
distrobox on  main [!⇡]
✦ ❯ ./distrobox create -i registry.fedoraproject.org/fedora-toolbox:36 f36-packaging
a3cc54e5a820b6bd95286ec142cb3eeab7f72b42cebf6fa0d3c0072035b3bca4
Distrobox 'f36-packaging' successfully created.
To enter, run:
distrobox-enter f36-packaging
distrobox on  main [!⇡]
✦ ❯ ./distrobox enter f36-packaging
Container f36-packaging is not runnung.
Starting container f36-packaging
run this command to follow along:
podman logs -f f36-packaging
Starting container...                  	 [ OK ]
Installing basic packages... …
```

Implement pre-initialization hooks

---

distrobox-export

The check that `--export-path` is also passed fails because the
`dest_path` variable used to store the argument does not have a
default value.
Fixes #274
```shell
distrobox on  fix-export-bin [!]
⬢ [fedora-toolbox:36] ❯ distrobox-export --bin /usr/bin/fedpkg
/usr/bin/distrobox-export: line 205: dest_path: unbound variable
An error occurred
```
```shell
distrobox on  fix-export-bin [!]
⬢ [fedora-toolbox:36] ❯ distrobox-export --bin /usr/bin/fedpkg
Error: Missing argument export-path.
An error occurred
distrobox on  fix-export-bin [!]
⬢ [fedora-toolbox:36] ❯ distrobox-export --bin /usr/bin/fedpkg --export-path ~/bin
/usr/bin/fedpkg from f36-packaging exported successfully in /home/michel/bin.
OK!
```
Signed-off-by: Michel Alexandre Salim <michel@michel-slm.name>

Fix distrobox-export --bin error handling

---

docs/compatibility.md
docs/useful_tips.md

Tested and worked fine. I had to install `dnf-plugins-core` which is
installed out of the box on AlmaLinux 8, but that's not a distrobox
issue.
```shell
distrobox on  main
❯ ./distrobox create -i docker.io/library/almalinux:9 -n alma9 --pre-init-hooks "dnf -y install dnf-plugins-core && dnf config-manager --enable crb && dnf -y install epel-release"
39a00b6fdacdbd22217fba9ff9c08a2468c8a57747f0df6e501ff057231899eb
Distrobox 'alma9' successfully created.
To enter, run:
distrobox-enter alma9
distrobox on  main
❯ ./distrobox enter alma9
Container alma9 is not running.
Starting container alma9
run this command to follow along:
podman logs -f alma9
Starting container...                  	[ OK ]
Executing pre-init hooks...            	[ OK ]
Installing basic packages...           	[ OK ] …
```

Add AlmaLinux 9 to tested containers distros

---

distrobox-init

this patch includes multiple fixes:
- the local repository no longer gets automatically updated. Other
package managers dont do this either and the output can include
something about an error, that isnt actually a problem, which causes
distrobox-init to fail.
- there are multiple curl packages for gentoo. net-misc/curl is the web
request tool.
- vte-profile doesnt exist for gentoo. The closest package is probably
vte.
- some packages compilation will report errors, which get ignored by the
build tools, so dont matter, but the mention will cause distrobox-init
to abort. To prevent this --quiet-build is used to supress to messages
from compilation

Fix gentoo support

---

distrobox-create
distrobox-host-exec
docs/README.md
docs/posts/execute_commands_on_host.md
docs/usage/distrobox-host-exec.md

Executing commands on the host, while inside of a container, can be done
either with flatpak-spawn, of playing tricks with chroot. Let's provide
a new script, which will be available inside of the container, that does
exactly that.
This tries to improve (although maybe not completely fix):
https://github.com/89luca89/distrobox/issues/177
Signed-off-by: Dario Faggioli <dfaggioli@suse.com>

distrobox-host-exec: new tool for host command execution

---

distrobox-create
docs/README.md
docs/usage/distrobox-create.md

This is a potential solution to #288, which gives
the user the chance to always create a new toolbox with
the latest most current image, instead of an old out-dated one.

create: prompt to download latest image by default

---

distrobox-init

Right now, on newer Ubuntu verions, systemd post-install hooks won't work if we keep host integration
Let's inject pre and post hooks in apt to temporary remove and restore host integration during installation
Signed-off-by: Luca Di Maio <luca.dimaio1@gmail.com>

init: fix apt hooks to make systemd install work

---

distrobox-host-exec

Reason why I created this PR: I have never seen a piece of software use [n/y]

host-exec: change [N/y] to [y/N]

---

distrobox-create
distrobox-enter
distrobox-rm
distrobox-stop

When someone tries to enter a container that does not exist, let's offer the option of just creating it ourselves. The main (only?) issue is whether to accept and, if yes, how to handle 'distrobox-create' options in 'distrobox-enter'.
As a first step, let's ingore the problem entirely and just invoke 'distrobox-create $container_name', in this case.
An improvement could be making 'distrobox-enter' support all distrobox-create parameter. Of course, that would be "just" the parsing of them, to stash them somewhere and, if we get to creating the container, pass them to 'distrobox-create'. That's easy enough to do, but it then means that every time we add/remove/modify a parameter of 'distrobox-create', we also need to do the same change in 'distrobox-enter' parsing code, which is not really …

Automatically create containers during 'distrobox-enter' (if they don't exist!)

---

distrobox-host-exec

Thanks to @1player, we now have a single-binary solution to replace
flatpak-spawn when not present.
Right now the solution is to ask to download the matching-version binary
from github releases.
This PR also implements the use of symlinks to make `distrobox-host-exec` execute as that command:
```console
~$: ln -s /usr/bin/distrobox-host-exec /usr/local/bin/podman
~$: ls -l /usr/local/bin/podman
lrwxrwxrwx. 1 root root 51 Jul 11 19:26 /usr/local/bin/podman -> /usr/bin/distrobox-host-exec
~$: podman version
...this is executed on host...
```
Fix #321
Signed-off-by: Luca Di Maio <luca.dimaio1@gmail.com>

host-exec: replace chroot with host-spawn

---

install
uninstall

Ever since `--prefix` was introduced in #190 (version 1.2.14), `--path` has been deprecated. 5 months have passed since, is it finally time to remove this relic of the past?

remove deprecated path feature

---

docs/distrobox_gentoo.md

There is an error message when using current dockerfile of gentoo.
> invalid from flag value portage: pull access denied for portage, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Obviously, the "portage" in the last line doesn't exist. Indicate gentoo/portage as portage to fix it.

docs: fix a mistake for gentoo dockerfile

---

distrobox-enter

When calling 'distrobox-create', from inside 'distrobox-enter' (in cause
automatic creation of the container is enabled) we were not "forwarding"
the '-r' flag properly. Therefore, when 'distrobox enter -r' was used,
we were trying to create a rootless container, which is obviously wrong!
Fixes: 8b195e3328d0a6fb19564555dec067c607fa8116
Signed-off-by: Dario Faggioli <dfaggioli@suse.com>

enter: fix automatic container creation when '-r' is used

---

distrobox-host-exec

See more details of the suggestion here. https://github.com/89luca89/distrobox/issues/362
Add a flag to distrobox-host-exec to skip the flatpak-spawn prompt. 
I've tried to keep the code high quality, and confirming to distrobox's conventions with comments and submitted a pull request with the changes. 
I added a --no-confirm/-nc flag. it doesn't force using host-spawn it just skips the prompt and tries to install host-spawn if flatpak and host-spawn are not installed.
I've made some minor changes to the wording of the prompt, including a line that directs people to the docs and added information about new flag to the options listed by the --help flag.

An implementation of the suggestion from issue #362 "Add a flag to distrobox-host-exec to skip the flatpak-spawn prompt"

---

distrobox
distrobox-export

Check a bit better the existence of a couple of things, such as directories and manpage entries, to avoid errors on distros where they may not exist (e.g., openSUSE MicroOS).

Add some checks for fixing issues due to dirs or manpages missing (on openSUSE MicroOS)

---

install

Some environments such as Ubuntu 22.04 don't have curl by default. Use
wget if curl is unavailable.

install: use either wget or curl

---

docs/compatibility.md

Desktop users might not know that their favorite distro's cloud image is tiny. Clarified post-creation instructions.

docs - Clarify smallness of common cloud images

---

distrobox-create
docs/README.md
docs/usage/distrobox-create.md

I have found myself not always needing the automatic application entry generation so I implemented a way to disable it

create: add --no-entry

---

docs/README.md

The placement of `else` does not make sense with the flow of the chapters. `Alternative methods` does not contain a prior statement which should be "else-d".

Redundant "else" in readme

---

distrobox-init

init: don't query filesystems mounted by beesd

---

docs/posts/execute_commands_on_host.md

this works:
```fish
> distrobox-host-exec podman version
Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.4
Built:        Thu Aug 11 22:42:17 2022
OS/Arch:      linux/amd64
```
this doesn't:
```fish
> distrobox-host-exec "podman version"
Failed to start command: Failed to execute child process “podman version” (No such file or directory)
```
Quote marks need to be removed in order for the integration to work.

Remove quote marks in fish tutorial

---

distrobox-create

When you try to use `distrobox-create --home` with a home directory that has a space in it, it errors out. This fixes that.

Fix using --home with space in path.

---

completions/distrobox
completions/distrobox-create
completions/distrobox-enter
completions/distrobox-ephemeral
completions/distrobox-generate-entry
completions/distrobox-list
completions/distrobox-rm
completions/distrobox-stop
completions/distrobox-upgrade

These files start with the #! sequence that marks interpreted scripts, but they are bash completion scripts that is merely intended to be sourced.
See https://lintian.debian.org/tags/bash-completion-with-hashbang
Signed-off-by: Michel Alexandre Salim <michel@michel-slm.name>

Remove shebangs from bash completions

---

distrobox

`distrobox --help` checks if man is present and acts as if `man distrobox` was executed by the user. Other commands do not exhibit this behaviour and I believe the wrapper should not be an outlier.
My belief is if a user wanted to open a manpage they would have called `man` themselves.

Do not open manpager automatically

---

distrobox-init

Closes: https://github.com/89luca89/distrobox/issues/445
Signed-off-by: Maciej Barć <xgqt@gentoo.org>

distrobox-init: fix vte installation; add --noreplace to prevent repeated builds

---

distrobox-init

and emerge --sync on updates
Signed-off-by: Maciej Barć <xgqt@gentoo.org>

distrobox-init: run emerge-webrsync if ::gentoo repo does not exist

---

docs/posts/run_latest_gnome_kde_on_distrobox.md

When trying the GNOME instructions (on Debian 11 Stable) I had to:
- manually create the folder /run/dbus in fedora-rawhide.
- add the flag -f to chown (otherwise it gave an `Operation not permitted` error) in fedora-rawhide.
- add the .desktop file to `/usr/share/xsessions` instead of `/usr/local/share/wayland-sessions/` for it to show in the login window. 
I also made the word host bold when talking about adding the .desktop entry, even if that should be obvious. Since all other instructions are inside fedora-rawhide, one might forget to exit before that step.
(Written from GNOME 43 on Fedora-Rawhide on Debian 11 Stable)

Small clarifications

---

extras/install-podman

I was having an issue with networking and found the configuration for cni_plugin_dirs wasn't being referenced. The configuration document suggests it needed to be in the [network] section. After moving it there, cni was able to find the plugins it said were missing.
https://github.com/containers/common/blob/main/docs/containers.conf.5.md#network-table

Fix cni_plugin_dirs

---

docs/posts/execute_commands_on_host.md

`command_not_found_handler` only checks for `$ZSH_VERSION` environment variable. To support bash as well, we need to check for `$BASH_VERSION` environment variable.
Plus, give a tip to ensure that the change has an effect as we do in the `fish` section.

Update handler function to support bash scripts

---

distrobox-enter
distrobox-export
docs/useful_tips.md

This enables the use of spaced arguments, quotes and special chars handling in both enter and export
Fix #439
Signed-off-by: Luca Di Maio <luca.dimaio1@gmail.com>

enter/export: handle quotes in arguments in a better way

---

distrobox-init

I noticed that `/etc/sudoers.d/sudoers` kept gaining a line every time the container started. I thus checked the init script and saw that the checked string doesn't match the printed string 😄 It prints `"user"` but only checks for `user` - this PR fixes that.
Thank you for creating and maintaining this!

init: fix sudoers spam (missing \" in check)

---

distrobox-init
docs/compatibility.md

Turns out that we can use the `stage3` image as a normal container. This (with the addition of `emerge --sync`) can solve the problem of providing and testing gentoo in the CI.
Signed-off-by: Luca Di Maio <luca.dimaio1@gmail.com>

compatibility: add gentoo docker image

---

docs/compatibility.md

Syntax mistake caused the "https://github.com/containers/toolbox" URL to have an extra `),` at the end, which makes the URL incorrect, and leads to a 404 page on Github instead of the real project page.

Fixed toolbox URL

---

distrobox-create

This is a small change but is helpful for users with specific images that have their own entry point defined for another purpose but building a distrobox using the same image would be helpful for debugging purposes. 
I've tested this on Ubuntu 22.04 running docker and I've checked that [podman-create](https://docs.podman.io/en/latest/markdown/podman-create.1.html) has the same option.

use --entrypoint to override entrypoint defined by image

---

.github/workflows/compatibility.yml
.github/workflows/main.yml
.github/workflows/manpages.yml
CONTRIBUTING.md
distrobox-create
distrobox-init
docs/README.md

Since the `--init-hook` and `--pre-init-hook` are the current method for resolving custom TLS certificates being needed by corporate proxies (see #493), being able to configure fixed hooks that don't need to be manually added on the command-line each time are useful.  
The variables already existed and could be overridden by the config files (which are just sourced into the scripts), but the `--pre-init-hook` was processed strangely and was appending the arguments needed when calling docker at argument parsing-time instead (see #497).  The command-line options override the config file options already, so no changes were needed for that.
Unrelated, but there was a typo in the `bashate` command in the CONTRIBUTING guide as well. 
/closes #497

Add init and pre-init hook defaults as supported config options

---

distrobox-init

After 039c4adae54ab, my init hook to ensure I can start accelerated VMs
by making sure that the container's user is part of a group with the
same group ID as the kvm group on the host no longer works.
Before:
```
$ distrobox create --init-hooks ...
$ distrobox enter ... -- groups
...
pi render
```
After:
```
$ distrobox create --init-hooks ...
$ distrobox enter ... -- groups
...
pi
```
This is due to the fact that `distrobox-init`'s new handling of
`--pre-init-hooks` is incorrect. It assumes that `--pre-init-hook` may
be passed with an empty value so it just shifts once when the next
argument is empty. Unfortunately, the empty value is still in the
arguments array so it will just be handled by the main loop on the next
iteration. As a result, the case will fall through to the default
case …

init: Fix init hooks after 039c4adae54ab

---

distrobox-generate-entry

The proper key is "Categories", per https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
The trailing quote seems to just be a copy-paste error from moving the lines around in 5d77405e5ffc89479cdc8e9b2d482e018c469885
I hope it's okay, I didn't open an issue for this as the fix seemed trivial I wasn't sure it was worth filing separately.

Fix typo and incorrect key for generated desktop entry `Categories`

---

distrobox-init

Hello, I started using Kali Linux over the distrobox soon. But every time I start the container, I noticed that the formation of Microsoft.PowerShell_profile.ps1 and prefs.xml files in my home directory. I noticed that there was a logical error on the code piece that formed the skel files in the distrobox-init file by researching the distrobox commands. In the Kali Linux /etc/skel folder, not only files. There are also folders. I threw PR to correct this problem.
Before:
After:

Fix skel support

---

distrobox-create

I recently discovered how `$DISTROBOX_HOST_HOME` was not being set properly due to a fault in #422

fix oversight in #422

---

CONTRIBUTING.md
distrobox-create
distrobox-enter
distrobox-ephemeral
distrobox-init
distrobox-list
distrobox-rm
distrobox-stop
distrobox-upgrade
docs/useful_tips.md

Up until now, we weren't able to distinguish between normal users (running the scripts via `sudo`) and **root** user (running the script in a login shell). This intruduces a check for the **SUDO_USER** variable (created in unmodified environments, by `sudo`), among other mechanisms, to allow the **root** user to manage _rootful_ containers.
This fixes #575.

Allow root user to run Distrobox

---

distrobox-host-exec

Download `host-spawn` only if it is missing or when the installed version is actually older.
Prior to this change `distrobox-host-exec` will download `host-spawn` even when the locally installed version is greater than expected.
For example `distrobox-host-exec` expected `host-spawn` version `1.2.1` and I have version `1.4.1` installed locally. Every time I call `distrobox-host-exec` it won't work unless I download the version `1.2.1`.
This shouldn't be happenning, considering that `distrobox-host-exec` prints that my version is older, when it is actually newer.

host-exec: bump host-spawn to 1.4.1 and do proper version comparison

---

distrobox-create
distrobox-enter
distrobox-export
distrobox-list
distrobox-rm
distrobox-stop
docs/usage/distrobox-export.md

Add the option (`-l` or `--login`) to `distrobox-export` so that the exported command runs inside a login shell, giving it access to the variables sourced during login (e.g: /etc/profile).
If `--sudo` is also specified, then care has been taken so that it also runs in a login shell (via -i).
Fixes #639

distrobox-export: add login shell option

---

distrobox-init

With these changes, on my openSUSE MicroOS box, `nvidia-smi` works:
```
dario@tw-nvidia-test:~> nvidia-smi 
Mon Mar 20 15:07:49 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.89.02    Driver Version: 525.89.02    CUDA Version: N/A      |
|-------------------------------+----------------------+----------------------+
... ... ...
```
And `glxinfo` seems to be happy too:
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: NVIDIA Corporation
server glx version string: 1.4
server glx extensions:
GLX_ARB_context_flush_control, GLX_ARB_create_context, 
GLX_ARB_create_context_no_error, GLX_ARB_create_context_profile,
... ... ...
```

init: improve NVIDIA integration when on openSUSE hosts

---

distrobox-create
distrobox-init
docs/compatibility.md
docs/usage/distrobox-create.md
docs/usage/distrobox-init.md
docs/useful_tips.md

This is a preliminary work to implement host's nVidia driver's integration, in the guest.
The procedure is simple enough, it will try and find all nVidia related files in the host, and bind mount them in the guest.
Right now this is confirmed working on:
- Ubuntu 22+
- Archlinux
- VoidLinux (glibc)
- Fedora
- Redhat/Centos/Family (7+)
This is confirmed NOT working on non-glibc distros like
- Alpine
- Debian -> Seems like it uses a dedicated nvidia directory in lib? Works on Ubuntu not on Debian
- Void (musl)
This needs more testing and confirmation, I don't have the hardware sadly.
Fix #477 #633 
Big thanks to @mirkobrombin for helping with the tests!
If anyone has suggestions to where to find a CI/CD that offers a machine with nVidia gpu, to do some automated testing, it will be great!

init: add nvidia integration

---

distrobox-enter

When the $PATH in host contain spaces, iterating with "for ... in ..."
will produce a wrong result.
refer to https://stackoverflow.com/a/44524309

enter: fix $PATH when it contains spaces

---

distrobox-create

* The `distrobox-*` executable scripts don't need to be in the same dir as the `distrobox-create` script. The only exception is the `distrobox-generate-entry` script. This change unifies the behavior.
* Fix script name: `distrobox-hostexec` -> `distrobox-host-exec`

Fix executable scripts lookup

---

.github/workflows/main.yml

Also, update `differential-shellcheck` to the latest version (`v4.0.2`) - https://github.com/redhat-plumbers-in-action/differential-shellcheck/releases Push events are supported since `v4.0.0`.
Fixes: https://github.com/redhat-plumbers-in-action/differential-shellcheck/issues/215
This should get rid of annoying messages from the `github-code-scanning` bot.

ci: trigger differential-shellcheck workflow on push

---

distrobox-create

this commit adds two new flags to "distrobox-create":
--unshare-netns
--unshare-ipc
both can be used to no longer share the respective namespace with the host.
Closes #608 
Signed-off-by: Louis DeLosSantos <louis.delos@gmail.com>

distrobox-create: allow the ability to "unshare" netns and ipc

---

distrobox-init

For example, these are not available on aarch64 CentOS Stream 9.

init: Only install mesa vulkan packages if available

---

install
uninstall

Makes the install prints more readable by not making it all red. Also shows the manpage path which gets used.
Only warns about PATH if `$dest_path` is not already in it.

More aesthetically pleasing install script

---

distrobox-enter

The current implementation of the quoting of the arguments does not work properly for many shell special characters. With the `git` command generated by `distrobox-export`, the following examples all result in errors.
```bash
$ git status '"`echo XXX`"'
/usr/lib/apx/distrobox-enter: 1: eval: echo XXX: not found
On branch main
nothing to commit, working tree clean
```
```bash
$ git status '"A&B"'
/usr/lib/apx/distrobox-enter: 1: eval: B": not found
On branch main
nothing to commit, working tree clean
```
```bash
$ git status '"(echo hello)"'
/usr/lib/apx/distrobox-enter: 1: eval: Syntax error: "(" unexpected
```
```bash
$ git status '"A;B"'
On branch main
nothing to commit, working tree clean
/usr/lib/apx/distrobox-enter: 1: eval: B": not found
```
To properly quote arguments, one can …

enter: fix the quoting of arguments

---

distrobox-create
distrobox-enter

Hey @89luca89 and everyone,
the current version of Fedora stable is [F38](https://www.redhat.com/en/blog/announcing-fedora-linux-38). Here I've updated the default toolbox images and usage examples to reflect that.
Thanks!

create/enter: bump default fedora-toolbox image to 38, update examples

---

distrobox-enter

With the current implementation, pathname expansions are performed for the contents of arguments. For example, with the `git` command (which is a distro_binary script generated by `distrobox-export` and passes the arguments to `distrobox-enter`), the following command results in the expansion of filenames in the current directory (even after the fix #697).
```bash
$ git commit -m ' * '
```
To fix this, the argument of `eval` needs to be quoted properly.

enter: fix unexpected pathname expansions

---

distrobox-list
distrobox-rm

* rm: add missing trailing newline
* list: reorder color reset
The color might not get reset at the end if no actual character is printed and the output has reached the bottom of the terminal.

terminal display fixes

---

distrobox-generate-entry

Commit 888d4561 ("generate-entry: add icon auto-download for known distros") added two printf statements printing the bare container name without any context.  This leads to superfluous on diststrobox-rm:
$ distrobox rm test_alpine
Do you really want to delete test_alpine? [Y/n]: y
test_alpine
test_alpine

generate-entry: drop apparent debug statements

---

distrobox-create

mounting the /etc/resolv.conf is problematic using podman and dnsmasq is setup with network manager, since it doesn't resolve the real dns and tries to use the local dnsmasq server, resulting on dns not working.
mounting these fields seems unnecessarily when not sharing the network

Ignore net files when unshare nets

---

docs/posts/integrate_vscode_distrobox.md

Updated name of extension in the Documentation, as it's changed names in the Visual Studio Code Marketplace, might cause some minor confusion.

Updated Extension Name

---

docs/posts/integrate_vscode_distrobox.md

`podman-exec` should be `podman-host` in this instruction
```
Open VSCode settings (Ctrl+,) and head to `Remote>Containers>Docker Path` and
set it to the path of `podman-exec`, like in the example
```

Fix typo in instructions for setting podman-host path

---

distrobox-rm
docs/usage/distrobox-rm.md

I might be wrong but the `--name` flag is never used in the source, so removing from the help message.
```
distrobox rm --name apx-alpine --force
ERROR: Invalid flag '--name'
distrobox version: 1.5.0.2
Usage:
distrobox-rm [-f/--force] container-name [container-name1 container-name2 ...]
Options:
--name/-n:		name for the distrobox
--force/-f:		force deletion
--rm-home:		remove the mounted home if it differs from the host user's one
--root/-r:		launch podman/docker with root privileges. Note that if you need root this is the preferred
way over "sudo distrobox" (note: if using a program other than 'sudo' for root privileges is necessary,
specify it through the DBX_SUDO_PROGRAM env variable, or 'distrobox_sudo_program' config variable)
--help/-h:		show this message
--verbose/-v:		show more …
```

Remove --name since never used

---

distrobox-init

This PR makes the following changes:
- Pacman repository cache is only updated once, at the beginning, instead of every command.
- Pacman will no longer re-install packages. Without the `--needed` argument, `pacman -S` will re-install packages.
- Pacman upgrades are no longer run every time. They only run if, from within the container, `distrobox-init --upgrade` is ran. This is the expected behavior.
This addresses performance concerns brought up here: https://github.com/89luca89/distrobox/issues/826
I manually tested this and can confirm that re-entering a stopped Arch Linux container is much faster and that upgrades still work.

Arch Linux speed improvements

---

distrobox-export

when you create a container using a diff home path, you export the app/bin into the container home rather than the host home, since the idea of exporting is to make available that application on the host system i think we need to export by default into the host_home instead.

Export to host_home by default

---

distrobox-export

when you have --sudo and not --login the start_shell is empty when we should have "sudo', this PR fixes that

fix: --sudo when not --login

---

distrobox-host-exec

Currently the script sets the `nounset` shell option, but it doesn't define the `CONTAINER_ID` variable and nor it should (something else does it). In such cases, we should resort to shell parameter expansion in order to use a default value (an empty string, in this case) if the parameter - read `CONTAINER_ID` variable - is unset or null.
So, we should use `${CONTAINER_ID:-}` instead, to avoid this error.
Fixes #882

host-exec: Fix CONTAINER_ID: unbound variable error

---

distrobox-export

Found an issue when distrobox-export when distrobox paths contain spaces that would cause the export file to point to the wrong location.  Encapsulating the path with quotations should fix this issue.

Should fix issues with paths containing spaces

---

distrobox-export

That's important to ensure exported applications will show up in whatever the user/DE is using desktop files for (taskbars, desktop menus, etc) right after exportation.
Desktop Environments should already install `update-desktop-database` by default - that's how they handle packages installing `.desktop` files. I'd believe that most Window Managers should also have it.

export: Add call to update-desktop-database tool

---

distrobox-upgrade
docs/usage/distrobox-upgrade.md

i created multiple instances for different projects, and updating all instances means starting all instances that some do heavy operations at startup, so i want to keep them up-to-date but only for the ones i'm currently using so i thought that --up variable could be useful to add for other/similar usages

Add a flag to upgrade only running instances

---

distrobox-rm

Only prompt the user to delete their mounted home directory (if it differs from $HOME) if they pass the `--rm-home` flag.
```
$ distrobox-rm -f acme
acme
```
```
$ distrobox-rm -f --rm-home acme
Do you want to remove custom home of container acme (/var/home/stone/Clients/ACME)? [y/N]: y
acme
Successfully removed /var/home/stone/Clients/ACME
```
This is a suggested solution to the pending discussion in issue #894 and resolves the issue raised in #895.

fix: Only prompt to delete home if `--rm-home` is passed

---

distrobox-init

If the image ships some untrusted repositories initial package installation might fail for these two separate reasons
1) The package list obtained with `zypper se` is polluted with warnings coming
from zypper itself about those untrusted repositories
2) Even with a correct package list, zypper would still return a non-zero exit
code to acknowledge those untrusted repositories
This commit tries to tackle both points. The reason of checking for the exit code rather than using `--no-gpg-checks` is that this way untrusted packages wouldn't get in without user intervention.

opensuse: init: handle untrusted repositories when installing basic packages

---

distrobox-export

Solves #482
- test if we are not in a container and run distrobox-enter if not
- test if we are in a container and if the container name is not the same as the one we are exporting from
- else run the binary

Make exported binaries runnable within other Distrobox containers

---

distrobox-init

https://github.com/89luca89/distrobox/blob/ace500978b8df4ff84f749a3be4723b64d13b9a4/distrobox-init#L190
`cat /run/host/etc/shadow > /dev/null` appears to always return true even when rootless.
This can be changed to check to see if `/etc/shadow` is writable to determine access. The earlier commit for checking readability (`-r /run/host/etc/shadow`) also always returned true.
```
> ls -l /etc/shadow
-rw-r--r--. 1 root root 1145 Aug  8 22:09 /etc/shadow
```
I believe this addresses the issue I had in #899 
Running `./distrobox ephemeral -i archlinux:latest -n test`
Log excerpt:
```
> podman logs -f test
+ '[' -w /run/host/etc/shadow ']'
+ '[' -n ' ' ']'
+ printf 'distrobox: Executing pre-init hooks...\n'
```
[distrobox-init fix.txt](https://github.com/89luca89/distrobox/files/12329659/distro …

Change rootful detection condition

---

distrobox-enter

Resolves #911 
when `XDG_DATA_DIRS` is empty
```bash
++ standard_paths='/usr/local/share /usr/share'
++ container_paths=
++ for standard_path in '$standard_paths'
++ pattern='(:|^)/usr/local/share(:|$)'
++ '[' -z '' ']'
++ container_paths=/usr/local/share
++ for standard_path in '$standard_paths'
++ pattern='(:|^)/usr/share(:|$)'
++ '[' -z /usr/local/share ']'
++ echo /usr/local/share
++ grep -Eq '(:|^)/usr/share(:|$)'
++ container_paths=/usr/local/share:/usr/share
++ set +x
```
when `XDG_DATA_DIRS` is not empty at the beginning
```bash
++ standard_paths='/usr/local/share /usr/share'
++ container_paths=/home/user/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share
++ for standard_path in '$standard_paths'
++ pattern='(:|^)/usr/local/share(:|$)'
++ '[' -z …
```

enter: fix `XDG_DATA_DIRS` and `XDG_CONFIG_DIRS` handling

---

distrobox-create
distrobox-export
distrobox-init

In a podman container, if the container environment variable is set, it
means you are in a container.
--mount type=tmpfs,destination=/run only in initful docker
It's required for systemd on docker, on podman it's taken care of
--systemd=always flag.

Add extra check to detect if we are in a container

---

docs/README.md
docs/compatibility.md

This is paricularly useful in the case of aarch64 Chromebooks, as there
is a lack of well upstreamed reasonably priced aarch64 machines.
aarch64 Chromebooks fill this gap well. This is using the built in
Linux on ChromeOS mode which is debian-based.

Add ChromeOS as supported host OS

---

docs/compatibility.md

It works better on Debian 12 bookworm, this requires an upgrade, all
repos in the environment have 12 versions including the Google
maintained one for cros-packages. But there is an option to use docker
and Debian 11 bullseye. Original testing was done on podman with Debian
12, both rootful and rootless.

docs: ChromeOS compatibility should say Debian 12 bookworm

---

docs/useful_tips.md

As written previously, Markdown would join the two lines into a one-line paragraph and show an invalid command.

fix code example

---

distrobox-enter

Similar problem to #911, that the way distrobox used now to append standard paths to container path is not working. This PR fix the problem with similar ways to #912 but changed the logic a little bit more. To preserve the order of both the host path and additional standard path instead of reversing them.
the `standard_paths="/usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin"` is left untouched.
Examples:
host PATH: `/opt/mambaforge/bin:/opt/mambaforge/condabin:/opt/devkitpro/tools/bin:/home/vm/.cargo/bin:/usr/local/sbin:/usr/bin:/sbin:/bin:/opt/go/bin:/snap/bin:/home/vm/.local/bin`
output `container_paths=/opt/mambaforge/bin:/opt/mambaforge/condabin:/opt/devkitpro/tools/bin:/home/vm/.cargo/bin:/usr/local/sbin:/usr/bin:/sbin:/bin:/opt/go/bin:/snap/bin:/home/vm/.local/bin:/usr/lo …

enter: use natural order from host PATH

---

distrobox-create
docs/usage/distrobox-assemble.md

This should ensure a basic unsharing between guest and hosts
**This is not a proper sandbox**
This allows to:
-unshare-devsys:          do not share host devices and sysfs dirs from host
-unshare-ipc:          do not share ipc namemspace with host
-unshare-netns:        do not share the net namespace with host
-unshare-process:          do not share process namemspace with host
And an `unshare-all` to do all the above.
This allows to have only the minimal requirements to:
- access user's HOME
- launch applications with GUI/GPU/Audio/Video
Additional mountpoints can be declared with `--volume`
For now **I'm not contemplating unsharing the home** that would be a bit too much and denaturalise the purpose of distrobox itself.

WIP: unsharing mode, work on #28

---

docs/compatibility.md

Bazzite: An OCI image that serves as an alternative operating system for the Steam Deck, and a ready-to-game SteamOS-like for desktop computers and living room home theater PCs. Bazzite ships with distrobox-git installed by default.
Bazzite Arch: A ready-to-game Arch Linux based OCI designed for use exclusively in distrobox.

docs(compatibility): Add Bazzite and Bazzite Arch as supported distros

---

docs/useful_tips.md

This PR contributes by providing the steps to run Waydroid in a Distrobox. I explained the requirements and provided two installation methods: manual and automated (using a pre-configured image).

Document Waydroid

---

docs/posts/install_podman_static.md
docs/posts/steamdeck_guide.md

Hi,
This PR aims to add the instructions to make the `podman` launcher binary executable, which were missing from the documentation. Related to https://github.com/89luca89/podman-launcher/pull/4
It also corrects a little typo in the title of the Steamdeck install guide.

Add missing instructions to make the podman launcher binary executable 

---

distrobox-assemble

With this '¤' volumes can be on multiple lines
```
volume="/abc:/abc "
volume="/def:/def"
```
basically the same as for `additional_packages` and `additional_flags`.

distrobox-assemble fix missing ¤ in volume handling

---

distrobox-export

Apparently, the export cannot handle filenames with quote, in my case it was the "...local/share/applications/Baldur's Gate 3.desktop" that caused the error in https://github.com/89luca89/distrobox/blob/9b4e7ec439544768a8e9a51675ec3f18465d5393/distrobox-export#L361
++ xargs '-I{}' grep -le 'Exec=.*steam.*' -le 'Name=.*steam.*' '{}'
++ xargs '-I{}' grep -Le 'Exec=.*/usr/bin/distrobox-enter.*' '{}'
++ xargs '-I{}' printf %s@ '{}'
xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option

Fix the issue when export would fail if there is a quote in filename(s).

---

docs/compatibility.md

There's a special distrobox-compatible flavor of openSUSE, see https://en.opensuse.org/Distrobox. This is configured as a default image when using distribution provided distrobox packages.

Update compatibility.md for openSUSE

---

distrobox-assemble

fix: distrobox assemble --name params cleanup missing.

---

docs/compatibility.md

Tested distrobox on Windows Subsystem for Linux today, works as is.

docs: Windows compatibility using WSL

---

distrobox-export

icon_name would always have a trailing '@', resulting in the hard path check to always fail.
Also moving the hard path check into the for loop for multi icon support.

export: fix hard path icon export

---

distrobox-init

Fixes #1029.
Mount points may have additional flags (e.g., `nodev`, `nosuid`) to check for. However, the function [`get_locked_mount_flags`](https://github.com/89luca89/distrobox/blob/bf65e627b7b5c9b505932a671618c378aa84c48f/distrobox-init#L211) exits immediately and returns an empty flag if the mount point is a file (e.g., `/etc/localtime`). If the original mount point is a file and it has any ["locked" flags](https://github.com/89luca89/distrobox/blob/bf65e627b7b5c9b505932a671618c378aa84c48f/distrobox-init#L239), then the file will fail to bind mount as read-only without those "locked" flags (in rootless mode).
I don't think it is necessary to exclude files when checking the mount flags. This PR removed that checking and updated the variable names to reflect the change.

init: fix mount flags for files (e.g., `/etc/localtime`)

---

distrobox-init

Fixes #995
Since at least Debian Buster (2019), libgl1-mesa-glx and libegl1-mesa are transitional packages for libgl1+libglx-mesa0 and libegl1 respectively.
In Debian Trixie, the transitional packages have been removed. Install the actual packages directly.
If you think that it would be better to add a check for even older releases I could add that as well (so that libgl1-mesa-glx and libegl1-mesa are installed on ancient releases), but I'm not sure if anyone has such an usecase :thinking:

init: debian: fix installation of deprecated libgl1-mesa-glx and libegl1-mesa

---

distrobox-assemble

when assembling	the following example file:
```
[fedora]
root=true
start_now=true
```
distrobox fails	to enter the container because it does not pass the --root flag. this commit fixes that.

fix: fixed assemble start_now option with root

---

distrobox-init

This PR fixes the error during the initialization of a Gentoo container. 
If user adds an `--ask` option to the `EMERGE_DEFAULT_OPTS` then they can not enter the Gentoo container anymore:
```
>>> Jobs: 0 of 0 complete                           Load avg: 0.04, 0.10, 0.12
+ deps='
zsh
app-crypt/gnupg
bash-completion
diffutils
findutils
less
ncurses
net-misc/curl
app-crypt/pinentry
procps
shadow
sudo
sys-devel/bc
sys-process/lsof
util-linux
wget
'
+ install_pkg=
+ for dep in ${deps}
++ emerge --search zsh
++ grep -Eo '[0-9]'
++ grep 'Applications found'
!!! "--ask" should only be used in a terminal. Exiting.
+ '[' '' -gt 0 ']'
/usr/bin/entrypoint: line 738: [: : integer expression expected
+ for dep in ${deps}
++ emerge --search app-crypt/gnupg
++ grep -Eo '[0-9]'
++ grep 'Applications …
```

Fix inability to enter Gentoo container after adding --ask to EMERGE_DEFAULT_OPTS

---

distrobox-create
distrobox-enter

Two commits:
- Read $XDG_CACHE_HOME, fall back to $HOME/.cache
- Change default cache dir from ~/.cache to ~/.cache/distrobox

Use $XDG_CACHE_HOME, keep cache files in $HOME/.cache/distrobox by default

---

distrobox-assemble

> See #1083
Based on the docs, it should be possible to provide a list to `exported_bins`. This PR addresses this issue and extends the functionality also to the `exported_apps`.
**Note:** This is my first PR to this project. Please don't hesitate to test and modify it to your standards.
By this fix, I was able to run the example shown in the referred issue.

FIX: Split multiple apps and bins by space

---

docs/compatibility.md

Updated the list of Fedora Images to properly reflect the location of Rawhide images, and Removed F36 as it's completely out of support

Updated URLS for Fedora Images, Removed F36

---

distrobox-create
distrobox-enter
docs/usage/distrobox-create.md
docs/useful_tips.md
man/man1/distrobox-create.1
man/man1/distrobox.1

Best-effort, search-and-replace. Checked manually using:
% rg -iC1 'fedora.*38'
Fedora 39 was released 2023-11-07 (about 2 months ago)
imho, 2 months is enough of a grace period.
Thoughts?
- Fixes 89luca89/distrobox#1119

Bump default container image to Fedora 39

---

distrobox-export

When exporting RStudio from a Fedora container, the resulting .desktop file contains the line
```
Exec=/usr/bin/distrobox-enter  -n rstudio -- /bin/sh -l -c  env RSTUDIO_DISABLE_CHECK_FOR_UPDATES=1 rstudio  %F 
```
Executing the file results in only `env` being executed. The command should be wrapped in quotes like
```
Exec=/usr/bin/distrobox-enter  -n rstudio -- /bin/sh -l -c  'env RSTUDIO_DISABLE_CHECK_FOR_UPDATES=1 rstudio  %F' 
```
This PR fixes that.

Capture full container command when exporting app

---

distrobox-assemble

Hey there,
not sure if this was intentional, but I would prefer to use `read` instead of `cat` since `cat` tends to break stuff from time to time (escaping)

fix(assemble): Use read instead of cat

---

distrobox-create
distrobox-enter
distrobox-generate-entry
distrobox-list
distrobox-rm
distrobox-stop
distrobox-upgrade

On NixOS, in order for the package maintainers to ship a default config file (as suggested [here](https://github.com/89luca89/distrobox/issues/978#issuecomment-1724077978)), the list of config files needs to be adjusted. 
None of the current config file paths are available from the derivation.
This PR essentially adds a config file path relative to the currrent script.
Ref: https://github.com/NixOS/nixpkgs/pull/268800

NixOS: Allow package maintainers to ship a static config file

---

distrobox-export

This PR allows the user to specify additional flags for `distrobox-enter` as described [here](https://github.com/89luca89/distrobox/blob/main/docs/usage/distrobox-enter.md) when using `distrobox-export`.
For example, I had the use case that I wanted the container not to run in the current working directory as this was a symlink from my root partition and thus not available inside the container. This would result in an error when starting the container.
Appending `--no-workdir` to the exported command was the solution.

Add --enter-flags to distrobox-export

---

distrobox-init

Doing a git-diff of my `~/.config/fish/` (on the host) , I found some mysterious additions to fish_variables (`SHELL`, `UID`, `MARONNE`). Thanks to the unique string "MARONNE", I was able to track down the culprit: an `/etc/fish/conf.d/config.fish` written (seven times) by distrobox-init.
"MARONNE" seems most likely to be the result of a find/replace with clipboard contents? The command that sets it is otherwise the same as the previous line.
And then I searched for "fish" in the bug tracker to see if this had been reported already, and found #1115, so I fixed that too.

Fish fixes

---

docs/useful_tips.md

The init-hook provided in the [useful tips documentations](https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md) for creating a distrobox with the the same hostname as its host has two typos:
- Command substitution wrapping `uname -n` suppressing stdout redirect
- trailing "`"
Using this init-hook as suggested causes build errors (see #1164). This fix corrects the suggested script by removing the command substitution and the trailing "`".
To elaborate: I think command substitution here is misplaced since `uname -n` already prints to stdout and can be redirected directly. Or you can use `echo` on the provided command substitution. Or you can use the `hostname` command. I.e.
`uname -n > /etc/hostname`
`echo "$(uname -n)" > /etc/hostname`
`hostname "$(uname -n)"`
Tested on …

docs: fix init-hook script for hostname matching

---

distrobox-init

This PR fixes a regression stemming from the [1.6.0](https://github.com/89luca89/distrobox/releases/tag/1.6.0) release, for further info refer to the #1128 issue.

Fix --nvidia flag unreliably mounts libraries into /usr (#1128)

---

distrobox-create

This should allow the user to use a modern terminal without installing anything additional inside the container itself but it will still prioritize terminfo from the container

Add host terminfo as a fallback

---

completions/bash/distrobox
distrobox
distrobox-init

Hi Luca,
This PR fixes the following:
1. Bash completions for the `distrobox` wrapper command
2. Auth cookie symlink in user integration for systemd/init containers
3. User integrations from being cleaned up by systemd when no session for the user is active, which causes future sessions to break (no access to wayland/pipewire, etc).
🚀

Fix bash completions and init/systemd user integrations

---

distrobox-export
distrobox-rm

~~In order to reliably handle paths with whitespace, quotes, or nonprintable characters, `find`, `xargs`, and `grep` should be configured to separate them using the NUL character rather than using newlines or ad-hoc escaping. (This is documented in the shellcheck linting rule SC2038, which documents a real issue and should not be disabled.)~~
Update:
In order to reliably process paths with whitespace or quotes to xargs without using non-POSIX features, each character must be escaped. (Quoting will handle whitespace, but not filenames with quotes in them.)

export & rm: correctly handle paths containing whitespace and quotes

---

distrobox-create
docs/usage/distrobox-create.md
docs/useful_tips.md

I thought it would require more changes but its already passed to podman so why not have it as an option when it requires so little work

Add --hostname argument and DBX_CONTAINER_HOSTNAME env var

---

completions/zsh/_distrobox-assemble
completions/zsh/_distrobox-create
completions/zsh/_distrobox-enter
completions/zsh/_distrobox-ephemeral
completions/zsh/_distrobox-export
completions/zsh/_distrobox-generate-entry
completions/zsh/_distrobox-init
completions/zsh/_distrobox-stop

Fixed issue where the completions were showing invalid syntax ex. '--additional-flags' and a few others were being incorrectly completed as '--additional-flags='

zsh completions: fixed issue with some arguments having invalid syntax

---

distrobox-init

Fedora recently changed their `passwd` implementation from its own package to the implementation in `shadow-utils`, adding `--stdin` in the process (which has been subsequently accepted upstream). Without that flag, entering up a Fedora container for the first time fails with
```
+ printf '%s\n%s\n' 7867745a-41ea-4493-8b7b-83d8fd18924a 7867745a-41ea-4493-8b7b-83d8fd18924a
+ passwd root
The password for root is unchanged.
Changing password for root
Enter the new password (minimum of 8 characters)
Please use a combination of upper and lower case letters and numbers.
+ '[' 1 -ne 0 ']'
+ printf 'Error: An error occurred\n'
Error: An error occurred
```
Look for `--stdin` in the help output of `passwd` and use it if it is supported so the root password is properly changed.
Closes: …

init: Add '--stdin' flag to 'passwd root' call if supported

---

.github/workflows/compatibility.yml
distrobox-enter
distrobox-init

Podman by default logs stderr as priority 3 journald errors. Don't know if other container managers do the same 😖
Github issue: https://github.com/containers/podman/issues/20728
`distrobox-create` by default enables verbose output for `distrobox-init` which causes the latter to output all xtrace output as priority 3 journald errors. 🤪
This PR redirects stderr in distrobox-init to stdout to prevent this *crazy* behavior. 😌

Prevent podman from logging stderr verbose output as priority 3 journald errors

---

distrobox-generate-entry

I noticed very weird errors about `distrobox-create` not finding container name after creating, and after checking out with `set -x` it turned out `podman` was being used for generating entry after creating container instead of `lilipod` (which i was expecting to be used with `DBX_CONTAINER_MANAGER` set)
This PR should fix that as now it respects that variable.

distrobox-generate-entry: respect DBX_CONTAINER_MANAGER variable

---

distrobox-init

Creating these variables as empty, could have negative impact on other programs. For example, it apparently breaks `gpg-agent` (https://lists.gnupg.org/pipermail/gnupg-users/2024-March/066956.html).
Fixes: https://github.com/89luca89/distrobox/issues/1249

Don't create empty XAUTH\* variables.

---

distrobox-export

Hi there. Just a small little thing I thought might be useful for others.
I keep Distrobox pretty concretely separated from everything else on my system, and that includes the binaries it exports. So I would want to pretty much always use `--export-path`, but it would be more convenient if the default value of that argument could be supplied by an environment variable. So I added precisely that: `DISTROBOX_EXPORT_PATH`.
Let me know if there's anything I should change or update in addition. The contributing guidelines mention testing, but it doesn't seem like Distrobox actually has a test suite. That said, I am using this particular change myself with success.
Thanks for your work on this software! 🙂

Add DISTROBOX_EXPORT_PATH env var for distrobox-export.

---

distrobox-init

Old zypper versions do not support "se -x". Use the equivalent "--match-exact" instead such that even distributions with old zypper versions can run in distrobox.

distrobox-init: use "zypper se --match-exact" (instead of "zypper se -x")

---

docs/posts/steamdeck_guide.md

Fixes #1270 
**References**:
https://steamcommunity.com/app/1675200/discussions/0/4208119548515682878/
https://www.reddit.com/r/SteamDeck/comments/1b4wkig/updating_the_builtin_distrobox/
https://www.reddit.com/r/SteamDeck/comments/t8al0i/install_arch_packages_on_your_steam_deck/
https://help.steampowered.com/en/faqs/view/671A-4453-E8D2-323C

Add info on upgrading package on steamdeck

---

docs/useful_tips.md

Fixed a typo (extra backtick) from the xhost command which let's you connect to the host xserver.

docs: remove extra ` from xhost command

---

distrobox-init

Instead of running `apk info` on each package individually instead just compare the list of requested packages to an `apk search` of them and pick the ones that could be found; perhaps something similar could be done for the other package managers as well to avoid such wasted time :p
On alpine due to the way searching for providers of `openssh-client` and exact matching of the found packages (`procps` is `procps-ng`) adjust these both accordingly to keep the end result consistent for alpine and wolfi.
On my end this halves the setup time for the non-toolbox alpine and wolfi images from ~30 and 40 seconds to ~15 and 20 seconds respectively.

init: massively speed up apk deps install

---

distrobox-enter

For the past week I've noticed issues where distroboxes will spontaneously crash in CLI, especially during a long process like system package updates. I find it difficult to reproduce consistently, but something like a large `paru -Syu` or `apt update && apt upgrade -y` for example, would almost always trigger the crash.
Upon trying to re-run the distrobox, the process would hang:
```
Starting container...                          
```
After interrupting with CTRL-C:
```
/usr/bin/distrobox-enter: line 514: /home/user/.cache/.ubuntu-distrobox.fifo: No such file or directory
```
[This comment](https://github.com/89luca89/distrobox/issues/610#issuecomment-1971360249) in #610 suggests that the original fix for this problem has been reverted. 
I've tried that out on my own system with this …

fix: missing .fifo logfile in distrobox-enter

---

distrobox-enter

The flag name is debatable but ill explain why i would like this feature to exist
_PATH should not be passed by default IMO_, but at least i would like there to be a way to remove it without writing more logic in .profile or .bashrc/.zshrc
This fixes the problem of having cargo, go packages on host get priority over the ones inside the container as my path looks like this
```
...
/home/sandorex/.cargo/bin
/home/sandorex/.golang/bin
/home/sandorex/.npm-packages/bin
...
/home/sandorex/.dbx/dev/.cargo/bin
/home/sandorex/.dbx/dev/.golang/bin
/home/sandorex/.dbx/dev/.npm-packages/bin
...
```
_container `dev` with `~/.dbx` prefix_

Add option to run with clean PATH

---

distrobox-export

Previously (for nearly two years since 4522f29?) attempting e.g. `distrobox-export -a htop` with a file/dir named `htop` in `$PWD` it would mistakenly get detected as the icon for the program, copied over to `~/.local/share/icons/` and attempted to be used by the `.desktop` file.
Not sure if this is following the spec exactly but it does fix this very odd issue I only noticed because I happened to have a local git tree checkout of a program in my `$HOME` and while there tried to export a launcher for it to my host and dug deeper when the icon was showing up as entirely blank in GNOME.

export: consider only absolute candidate icon paths that exist

---

distrobox-export

When deleting an export that doesn't exist, the script would instead export the application.
Fixes #1332

export: cancel export when trying to delete

---

distrobox-init
docs/compatibility.md

For more details check the commit descriptions. Originally this just had `apt` changes, let me know if I should split the others to different PRs.
Similar to the previous `apk` optimization (#1298) instead of checking each package one by one instead grab the matching ones from `apt list` and pass them directly over to `apt-get install`.
On Arch we can `grep` the `pacman -Ssq` output (all packages) for the ones we're interested in.
`--needed` was already used previously but was dropped with bdf78c39f2bd71296d85da2f0b4a0b7a9624e20c, commented there as well.
Similar to Arch on Void we can instead `grep` the `xbps-query -Rs '*'` output (all packages) for the ones we're interested in after filtering out install status, description and versions.

init: massively speed up apt/pacman/xbps deps install

---

distrobox-enter

Tested as working on Chimera Linux with FreeBSD `date(1)` and Alpine Linux with busybox `date(1)` which both cannot report nanoseconds or timezone with `:` separator only supported on GNU coreutils which handles these extensions via a `strftime()` wrapper in gnulib.
Digging deeper in https://github.com/mirror/busybox/blob/master/coreutils/date.c technically busybox *can* support at least nanoseconds if the Alpine one was compiled with `CONFIG_ENABLE_FEATURE_DATE_NANO=y`, but it's not and `%N` is still not portable. Besides I can't think of a situation where reading log output would need sub-second accuracy so in my eyes this should be perfectly fine.
https://docs.podman.io/en/stable/markdown/podman-logs.1.html#since-timestamp lists some of the other supported formats, I basically picked …

enter: make log_timestamp date format universally compatible

---

distrobox-init

this fixes the profile creation for the fish shell on distributions like Gentoo that do not create `/etc/fish/conf.d` when fish is installed and allows entering with fish as the login shell
fixes #1347

init: add explicit creation of /etc/fish/conf.d 

---

.gitattributes
.github/dependabot.yml
.github/workflows/compatibility.yml
.github/workflows/main.yml
.github/workflows/manpages.yml
docs/README.md

- Bump CI action across all workflows. (Added a dependabot configuration file to automatically check for updates monthly and dependabot will create a PR if there is a new version of the action)
- Set the default end of line (eol) to LF in `.gitattributes`.
- Minor fixes and changes to README.

chore: bump CI actions, minor fixes to README and other files

---

install

GNU arguments `-D` and `-t` are respectively either not implemented or different in [FreeBSD `install(1)`](https://man.freebsd.org/cgi/man.cgi?query=install&sektion=1&format=html) which is used on [Chimera Linux](https://chimera-linux.org); use the options that are known to be compatible between the implementations.
Should also help with #615.

install: use more portable install(1) arguments

---

distrobox-init

This v2 of the PR.
In previous version I assumed that the issue was absolute path
in SHELL variabe. Leaving only the basename eliminated the hanging on start
but subshell still didn't work.
After doing additional testing I figured that that wasn't the issue.
The issue of broekn shells seems to be related to duplicate inclusion of distrobox hooks
when profile.d available.
While provided patch works a more comprehensive solution might be required to cover all cases.
In general we should inject hooks only once (first start or creation).
Since injecting on every start prevents customization of the container by the user
and can make it very difficult to identify shell/profile related issues (ask me how I know ;-))

Fix SHELL using absolute path and disable duplicate profile inclusion

---

docs/useful_tips.md

docs: fix `subuids` spelling mistake

---

docs/README.md

This separates the `curl` and `wget` install commands in the readme to make it easier to use the github copy button on the code view to copy the command.

Seperate curl and wget commands

---

docs/compatibility.md

23.04 was mentioned as supported, but the url wasn't provided. urls are source of truth for `--compatibility`, hence the addition.

compatibility: add missing url for ubuntu:23.04

---

docs/useful_tips.md

This is a simple fix, I just replaced a redirection with a pipe to `sudo tee`, because the command as-is does not work unless you run it as root (which doesn't seem to be the intended usage for that step-by-step).

Fix issue with user not having permissions to write containers.conf

---

distrobox-init

For fix error like below:
```
+ deps='
bash
app-crypt/gnupg
diffutils
findutils
less
ncurses
net-misc/curl
pinentry
procps
shadow
sudo
sys-devel/bc
sys-process/lsof
util-linux
wget
'
+ install_pkg=
+ for dep in ${deps}
++ emerge --search bash
++ grep 'Applications found'
++ grep -Eo '[0-9]'
+ '[' '2
0' -gt 0 ']'
/usr/bin/entrypoint: line 553: [: 2
0: integer expression expected
+ for dep in ${deps}
++ emerge --search app-crypt/gnupg
++ grep 'Applications found'
++ grep -Eo '[0-9]'
+ '[' 2 -gt 0 ']'
+ install_pkg=' app-crypt/gnupg'
+ for dep in ${deps}
++ emerge --search diffutils
++ grep 'Applications found'
++ grep -Eo '[0-9]'
+ '[' 2 -gt 0 ']'
+ install_pkg=' app-crypt/gnupg diffutils'
+ for dep in ${deps}
++ emerge --search findutils
++ grep 'Applications found'
++ grep -Eo '[0-9]'
+ …
```

fix: init package in Gentoo Stage3 image

---

distrobox-init

If `findmnt` does not exist (or returns an error), "Setting up read-only mounts" in `distrobox-init` fails with "Error: An error occurred".
Treat missing `findmnt` the same way as if the file/directory cannot be read.
It seems like some error handling for failing `findmnt` was already forseen:
```
flags="$(findmnt --noheadings --output OPTIONS --target "${src}" || :)"
```
However, the code apparently cannot handle `flags=":"`.
I'm completely unsure if my approach is reasonable or which implications it might have but it allows to at least enter the distrobox.

init: do not fail in "Setting up read-only mounts" if findmnt does not exist

---

distrobox-init

I tried running SteamOS using distrobox, but I found that every time I entered, distrobox-init would attempt to `Installing basic packages`. Without a network connection, SteamOS couldn't start. I eventually discovered the cause: the `ping` command was always unavailable, because the `iputils` package, which provides the `ping` command, was not installed.

add iputils in setup_pacman

---

distrobox-enter
distrobox-rm

When I was trying to use distrobox with rocm/pytorch:latest I've noticed the following error 
```
Error: template: inspect:3:27: executing "inspect" at <slice . 0 5>: error calling slice: index out of range: 5
```
It turns out this image has an environmental variable CI=1, that causes an exception when distrobox-enter / distrobox-rm is used with this docker image
Added some additional ifs to the corresponding commands to handle this case

Fix distrobox-enter and distrobox-rm to handle containers that have environment variables shoter than 5 symbols

---

distrobox-generate-entry

`$XDG_CONFIG_HOME` was already being used in a similar way, but anyway this makes it follow `$XDG_DATA_HOME` before defaulting to `~/.local/share` for the icons and .desktop files. 
Yes I don't have `~/.local/share` 😆

 generate-entry: use XDG_DATA_HOME

---

distrobox-export

Swaps if condition resulting in the matching environment variable being iterated

export: Fix XDG_DATA_DIRS and XDG_DATA_HOME handling

---

distrobox-init

When used on a Universal Blue OS like bluefin, the repo configurations are available at `/run/host/etc/yum.repos.d/`. Repos that contain the name nvidia are incorrectly bind-mounted into the container and causes weird errors on boxes using yum and dnf.
See the issue at https://github.com/ublue-os/bluefin/issues/1552

Exclude repos from bind-mounting

---

distrobox-export

This fixes the use of `XDG_DATA_DIRS` and `XDG_DATA_HOME` in accordance to the specification.
As per the [specification](https://specifications.freedesktop.org/basedir-spec/0.8/#basics)
> There is a set of preference ordered base directories relative to which data files should be searched. This set of directories is defined by the environment variable `$XDG_DATA_DIRS`.
and
> There is a single base directory relative to which user-specific data files should be written. This directory is defined by the environment variable `$XDG_DATA_HOME`.
This change now uses the correct fallbacks for each variable (was swapped) and does not try to iterate over `XDG_DATA_HOME` as it should only contain a single directory.

export: Actually fix XDG_DATA_DIRS and XDG_DATA_HOME handling

---

distrobox-create

distrobox fumbles the error handling for container creation.  the exit command is nested inside of the creation success conditional statement.  this PR adds an else statement and handles the subprocess error by passing it up
changes:
- print error message and exit with subprocess return code
here's the output now that the error is handled:
```
jardon@lagann:~/Projects/distrobox$ ./distrobox create --additional-flags jammy      --image docker.io/library/ubuntu:jammy --name apx-test --no-entry --yes --pull 
Trying to pull docker.io/library/ubuntu:jammy...
Getting image source signatures
Copying blob 857cc8cb19c0 skipped: already exists  
Copying config 53a843653c done   | 
Writing manifest to image destination
53a843653cbcd9e10be207e951d907dc2481d9c222de57d24cfcac32e5165188
Creating …
```

fix:[#1525] handle container creation failure

---

distrobox-enter

**TLDR:**
`distrobox-enter` is slow. I did some timing of the code using [the original but timed](https://github.com/TigerGorilla2/distrobox/blob/335a1586207b17185c7447f3e6486125e8faa51b/distrobox-enter) and [slightly modified](https://github.com/TigerGorilla2/distrobox/blob/d022acae9194d30211c78ccacaf3a216a90151fd/distrobox-enter#L727) but eventually came to the improvements proposed by this PR.
**Long version:**
I had noticed that my command to launch a terminal
> `distrobox-enter home -- foot`
has become slower but especially so on my laptop, taking multiple seconds.
I then eliminated `foot` by running `time distrobox-enter home -- true`. It was still slow. So I tried to launch the `podman-exec` manually and it only took ~250ms instead of 2-3 seconds.
Now I was pretty sure it was on …

distrobox-enter: improve cmd composition speed

---

distrobox-init

Example: distrobox create -i ubuntu:18.04 -n ubuntu18
Closes: #1621

init: fix runtime sync fallback

---

distrobox-enter

Since the latest release distrobox-enter does not work on system without tac command, this should make it more portable.
`tac` is GNU coreutils specific command - it is not present in bsd utils. There is also `tail -r`, but the parameter is not POSIX compliant.

Replace tac with awk to be more portable

---

distrobox-init

Description:
The $HOST_LOCALE contains the '-' symbol, but the output of locale -a does not include this symbol, which leads to repeated updates when updating the locale.
Log:
fixed can correctly skip over these duplicates update.
```
+ [ -e /etc/locale.gen ]
+ locale -a
+ grep -qi en_us.utf8 
+ locale -a
+ echo zh_CN.UTF-8
+ tr -d - 
+ grep -qi zh_CN.UTF8 
```

fix:repeat trigger update locale when locale exists

---

completions/zsh/_distrobox
completions/zsh/_distrobox-assemble
completions/zsh/_distrobox-create
completions/zsh/_distrobox-enter
completions/zsh/_distrobox-ephemeral
completions/zsh/_distrobox-export
completions/zsh/_distrobox-generate-entry
completions/zsh/_distrobox-host-exec
completions/zsh/_distrobox-init
completions/zsh/_distrobox-list
completions/zsh/_distrobox-rm
completions/zsh/_distrobox-stop
completions/zsh/_distrobox-upgrade
completions/zsh/_distrobox_containers
completions/zsh/_distrobox_images
completions/zsh/_distrobox_running_containers

zsh completions reworked. fixed not completing container names.

---

docs/useful_tips.md

Podman requires certain privileges to work properly inside a container, suggest to use a rootful Podman or Docker.
See [this] for some context.
[this]: https://bugzilla.suse.com/show_bug.cgi?id=1231231

docs: update Podman inside Distrobox

---

distrobox-assemble
docs/usage/distrobox-assemble.md

Closes #1617
Added ability to clone an existing Distrobox when using the distrobox-assemble command.

Added clone in distrobox assemble

---

docs/compatibility.md

url: https://hub.docker.com/r/linuxdeepin/deepin/tags

docs: add deepin 23 docker image

---

distrobox-enter

FPATH shell variable is used by zsh for looking up shell function definitions. 
Proposed change stops importing host FPATH environment variable into container. FPATH is supposed to be shell variable only and should not even be exported into shell environment in the first place. But in a case where it was exported this will stop propagating host FPATH value into container where it might collide with and overwrite proper guest FPATH contents.

Stop importing zsh FPATH into container

---

docs/compatibility.md

As above, I'm just adding distrobox-bpftrace to the openSUSE's supported images list.

docs: add distrobox-bpftrace openSUSE's image to the docs

---

docs/README.md

This is a fix for a tiny typo, changing "you" to "your" in the tect and the useful_tips.md# section.  It was causing the documentation to not scroll to the correct section.

Fix a small documentation typo s/you/your/

---

.github/ISSUE_TEMPLATE/bug_report.md
.markdownlint.yaml
docs/useful_tips.md

Since `markdownlint` added new rules that are rendering the CI red, I felt like fixing it :heart:

docs: fix markdown lint

---

distrobox-stop

Noticed this while doing some completions for Fish.  Looks like the `--name` argument was removed, but this usage example stayed the same.

docs: Remove --name argument from distrobox-stop usage docs

---

docs/README.md

In https://github.com/89luca89/distrobox/pull/1645, I updated the anchor link but failed to realize there was another reference to it elsewhere. Whoops...

Fix broken Useful tips link

---

.github/workflows/compatibility.yml

Since these images tend to be _very_ flaky with distrobox we declare them compatible but we don't want to have a red CI just because of them :innocent:

ci: ignore Neon and SteamOS when testing images

---

docs/compatibility.md

Debian 13 official distrobox images are out :+1:

docs: add debian 13 (toolbox) to the manual

---

distrobox-enter

Replace whitespaces with escaped whitespaces and switch to using sed to prepend --env to the env variables.

enter: Allow whitespaces in environment variables

---

distrobox-init
docs/compatibility.md

At last adds proper support for https://chimera-linux.org guests via https://hub.docker.com/r/chimeralinux/chimera.
I don't really like how `/etc/doas.conf` (or `/etc/sudoers.d/sudoers` for that matter) are being rewritten on every fresh enter of the container: is there some technical reason for this? I've duplicated it over to the `doas` logic but it didn't necessarily seem required; required stuff could be appended conditionally if missing but oh well.
Closes #1166.

Support Chimera Linux guests

---

distrobox-init

[`base-core-man`](https://github.com/chimera-linux/cports/blob/8f4bf92/main/base-full/template.py#L120-L121) has been transitional provider of this for a while and will eventually be dropped; I must've still copied this over from a much earlier version of the #1778 patch when I was experimenting long ago

init: setup correct chimera base-full-man dep

---

distrobox-init

This fixes minute long start-up hangs when using distrobox on a host that has active schroot mounts, which I saw on my machine.

init: exclude schroot mountpoint from socket search, improve performance.

---

distrobox-create

The current usage documentation for `distrobox-create` suggests that `--root` is the "preferred" way over `sudo distrobox`, but the code explicitly blocks `sudo` and `doas` calls. This change clarifies that `--root` is the only supported method.

chore: clarify --root documentation for distrobox-create

---

distrobox-create

In https://github.com/89luca89/distrobox/pull/1845 my editor accidentally replaced some tabs with spaces. This pull request fixes this mistake.

fix: indentation for --root usage in distrobox-create
