- README.md
- distrobox-create
- distrobox-enter
- distrobox-export
- distrobox-init
- install
FIX #3 
Verify each path before mounting it
Fix #4 
Add missing basename to file variable
> Fix mount routine

- .github/workflows/main.yml
- README.md
- distrobox-create
- distrobox-enter
- distrobox-export
- distrobox-init
- install
Check it out.
If it's fine for you, i'll add immediate action prompts for all those error messages/command requests, so the user could use it right away without worrying about the rest
> added automatic pull for missing images

- README.md
Some small noticed with vim's spellcheck feature. You can copy the changes and push them with a bigger commit.
> Fix some small typos on README.md

- distrobox-create
- distrobox-enter
- distrobox-export
- distrobox-init
> fix: add recursive copy for application's icons

- distrobox-create
> create: fix difference between HOME and PWD path resolution

- distrobox-create
I added a little space in the y/n question. In my opinion it looks a lot better.
> boolean: add space in y/n question

- distrobox-create
- distrobox-export
> export: fix closing quotes for exec command

- distrobox-enter
> enter: ensure PATH is built correctly and check for exact subpaths

- distrobox-create
- distrobox-enter
- distrobox-export
- distrobox-init
> create/export: use custom env variable to maintain original home path for exports when using custom home (#86)

- distrobox-create
- distrobox-enter
- distrobox-rm
- docs/usage.md
> all: support specifying name without --name/-n flag

- distrobox-init
- docs/compatibility.md
- docs/gentoo_guest.md
> init: add support for gentoo

- install
> rm -rf instead of rm -f

- distrobox-init
> init: initial clearlinux support

- distrobox-create
> create: default to Y

- docs/README.md
Just a little fix for usage.md path on README.md
> Fix usage.md url on README.md

- distrobox-create
Resolves #144 
@nathanchance can you test if this resolves? Thanks
> create: follow /dev/shm symlinks if present

- distrobox
Basic implementation of #164.
Hopefully it's good enough.
> distrobox: version flag

- install
- uninstall
Resolves #166.
I've also added a `successfully installed` message.
> install: conditional default install path

- docs/README.md
I have updated the installation part of the readme to reflect the conditional installation location previously implemented.
> README: Installation update

- docs/README.md
> New Logo proposal

- distrobox-init
- docs/distrobox_custom.md
This will be useful to use git signing, gpg integration inside a container
> init: add pinentry to base package list

- distrobox-init
> init: move some mountpoints as rw to avoid mount Unknown error 5005.

- docs/README.md
Changed "6 commands" to "7 commands" in the readme.
> readme: change command count

- distrobox-enter
> enter: improve logging steps

- docs/README.md
> fix README command count typo

- distrobox-stop
Signed-off-by: Mišo Barišić <me@misobarisic.com>
> stop: update misleading comment

- docs/posts/run_latest_gnome_kde_on_distrobox.md
Clarify systemd session language
> Docs: Update gnome instruction 

- docs/posts/run_latest_gnome_kde_on_distrobox.md
Signed-off-by: Mišo Barišić <me@misobarisic.com>
> docs: typo fix

- distrobox-list
- docs/usage/distrobox-list.md
I believe explicitly specifying a `no-color` mode should be available as well.
Extends #352
> Add no-color flag to list

- docs/compatibility.md
- docs/useful_tips.md
Host:
- distrobox for Debian is in testing
- update Ubuntu versions
Guest:
- Rocky 9 is available
- update useful_tips.md examples for pre-init-hooks
Signed-off-by: Michel Alexandre Salim <michel@michel-slm.name>
> Update host and guest lists

- docs/README.md
- docs/useful_tips.md
Inspired by this issue: https://github.com/89luca89/distrobox/issues/476#issuecomment-1277486593
Why not add some tutorials for it?
---
Problems:
- Only works with Podman. I don't use Docker so I don't know how Docker works with SystemD.
- Only works with SystemD. I don't use other init systems, I don't even know if alternate init systems provide similar functionality or not.
> [Docs] Add resource limitation tips

- docs/README.md
Changed `/home/.local` to `$HOME/.local`
> Fix example configuration file

- docs/README.md
closes https://github.com/89luca89/distrobox/issues/654
> List wget as an alternative install option

- distrobox-init
Not sure if there should also be a check if this exists on host.
> fix(nvidia): mount libcuda.so*, this matches nvidia-container-toolkit

- docs/README.md
Sorry, just noticed and cannot go away with it :P
> fix: typo in readme

- docs/compatibility.md
> Correct spelling of unprivileged

- distrobox-init
- docs/compatibility.md
This will improve compatibility with old/new versions and naming Fix #763
> init: search for packages availability before installation

- distrobox-export
reopening  #760  after watering the branch 
please review this comment https://github.com/89luca89/distrobox/pull/760#issuecomment-1588193431 this fix is actually need it
> Fix issue when a symbolic link points to a non-existing file

- docs/posts/run_libvirt_in_distrobox.md
> missing quote in run_libvirt_in_distrobox.md

- docs/compatibility.md
Also, ```distrobox``` is now in the Debian 12+ repos
> Debian is now at version 12

- docs/useful_tips.md
> docs: update useful_tips.md

- distrobox-enter
- distrobox-rm
- distrobox-stop
🦅 
```
Do you really want to stop  ubuntu? [Y/n]:
```
---->
```
Do you really want to stop ubuntu? [Y/n]:
```
---
```
Do you really want to delete containers:  ubuntu? [Y/n]:
```
---->
```
Do you really want to delete containers: ubuntu? [Y/n]:
```
> Remove extra white space

- distrobox-rm
> rm: Ignore nonexistent `~/.local/bin`

- docs/README.md
I minor Pull Request that updates @daudix's username (`daudix-UFO` -> `daudix`)
> minor: Updated Daudix's username

- distrobox-init
Just making the style of the fish script more fish-like and consistent within itself.
Fixes: #1252
> Fix a nit.

- install
Hi, I was trying to update to the latest git version on Bazzite and noticed the installation script was failing when trying to install icons, these changes fixed it for me when installing to `$HOME/.local`
> Fixes installation script

- distrobox-init
- docs/compatibility.md
The "C library diversity" is one of the  main points listed on https://voidlinux.org so we might as well support it here too :)
> Support musl variant of Void Linux

- distrobox-init
sudo has been merged into Wolfi, add it for parity with Alpine
> chore(init): Add sudo to Wolfi

- docs/posts/run_libvirt_in_distrobox.md
support for 3d acceleration
_(reopened due to name change of the branch)_
> support for 3d acceleration in: run_libvirt_in_distrobox.md

- distrobox-export
> fix for 1440

- distrobox-export
I ran into an issue when exporting. I mentioned it here: https://github.com/89luca89/distrobox/issues/1097#issuecomment-2463285814
I have reworked a small part of the code to utilize the `-0` option of `xargs`
I want to know if there are any tests that I need to do to make sure everything is ok since I could not find any.
> potential improvement to pull-request #1102

- distrobox-init
> make the default fish_prompt an autoloaded function

- distrobox-host-exec
fix https://github.com/89luca89/distrobox/issues/1786
> fail for HTTP response codes >= 400 (curl --fail)

- docs/compatibility.md
> docs: fedora 42

- distrobox-init
> fix: create xdg-open distrobox-host-exec symlink only if --init not used
